/**
 * @author Jacky Feng
 * @date 2024/3/17 16:46
 */
package top.fexample.qchat.common;

public interface MessageType {
    String CONNECT_SERVER_TIMEOUT = "CONNECT_SERVER_TIMEOUT";
    String LOGIN_SUCCESS = "LOGIN_SUCCESS";
    String LOGIN_FAIL = "LOGIN_FAIL";
    String REGISTER_EXIST = "REGISTER_EXIST";
    String REGISTER_SUCCESS = "REGISTER_SUCCESS";
    String REGISTER_ERROR = "REGISTER_ERROR";
    String COMMON_MESSAGE = "COMMON_MESSAGE";
    String GET_ONLINE_FRIEND = "GET_ONLINE_FRIEND";
    String RECEIVE_ONLINE_FRIEND = "RECEIVE_ONLINE_FRIEND";
    String REQUEST_FRIEND = "REQUEST_FRIEND";
    String RECEIVE_FRIEND_REQUEST = "RECEIVE_FRIEND_REQUEST";
    String CLIENT_EXIT = "CLIENT_EXIT";
}